### PR TITLE
WIP: Semantic dev

### PR DESCRIPTION
**Pull request by outloudvi**
[Work in progress]
(Please report stuffs to #3.)

### CODE REVIEW

**Comment by outloudvi** [comment]
大 型 R e b a s e 不 可 避

**Comment by SchrodingerZhu** [comment]
login page now has fonts source not found errors.

**Comment by SchrodingerZhu** [comment]
fixed after new cdn config is up.

**Comment by SchrodingerZhu** [comment]
* [x] profile
* [x] contests page
* [x] comments (done at 1d5cafb2, should be more prettier)
* [x] organization 
* [x] copy button for sample code in description
* [x] fix the last page of the problem list (strange layout on my side).  (fixed at `613ea0e`)
* [x] code region background
* [x] float plugin of contest info
* [x] button of contest exit
* [ ] checkbox of organization on users page at contest mode

**Comment by outloudvi** [comment]
@SchrodingerZhu That's a weird trick... Semantic-UI has a `dist/` and their `dist/` goes to 2.4.2. However, 2.4.2 is not tagged and released so cdnjs doens't know there is a 2.4.2 :D

**Comment by outloudvi** [comment]
@SchrodingerZhu 

* comments -> will fix later
* fix the last page of the problem list (strange layout on my side). -> Plz screenshot it, or tell me the steps to reproduce
* code region background -> currently half-fixed
* checkbox of organization on users page at contest mode -> Don't get it...

**Comment by SchrodingerZhu** [comment]
@outloudvi Impersonate Button disappeared.

**Comment by SchrodingerZhu** [comment]
> @SchrodingerZhu
> 
>     * comments -> will fix later
> 
>     * fix the last page of the problem list (strange layout on my side). -> Plz screenshot it, or tell me the steps to reproduce
> 
>     * code region background -> currently half-fixed
> 
>     * checkbox of organization on users page at contest mode -> Don't get it...

1. just click the page 6. I found unclosed `<div>`.
2. join the contest mode and click the users, the checkbox is just at the top.

**Comment by outloudvi** [comment]
@SchrodingerZhu I think the major modification is done. It would be great if you can have some check.

(Please recheck "checkbox of organization on users page at contest mode")
(Gravatars show weird in `/problem`, that's confirmed and will be done later in the week.)

**Comment by outloudvi** [comment]
Superseded by #15.

**Pull request closed without merging**
