### PR TITLE
Upstream sync, til ffe1170

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Closes #811.

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
@outloudvi Plz have a luk at dis.

**Review by outloudvi — APPROVED** [review]
That's a change of rating calculation algorighm. It seems to be okay in syntax and somehow make sense.
I personally don't know about TopCoder or something...

**Comment by outloudvi** [comment]
Ehh but plz merge it later

**Comment by SchrodingerZhu** [comment]
@outloudvi [TopCoder](https://www.topcoder.com/)

**Comment by SchrodingerZhu** [comment]
@outloudvi I will keep this pr just to show all the commits made by upstream during your work.

**Pull request merged**
